//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssignment
    {
        public int ID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public string PDF { get; set; }
        public string Grade { get; set; }
        public int PeriodID { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Class Class { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
