//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Video1 { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
